config-version: 2

name: 'apple_search_ads_source_integration_tests'
version: '0.1.0'

profile: 'integration_tests' 

vars:
  apple_search_ads_source:
    organization: "{% if var('generating_docs','no') == 'yes' %}{{ source('apple_search_ads','organization') }}{% else %}{{ ref('organization_data') }}{% endif %}"
    campaign_history: "{% if var('generating_docs','no') == 'yes' %}{{ source('apple_search_ads','campaign_history') }}{% else %}{{ ref('campaign_history_data') }}{% endif %}"
    campaign_report: "{% if var('generating_docs','no') == 'yes' %}{{ source('apple_search_ads','campaign_report') }}{% else %}{{ ref('campaign_report_data') }}{% endif %}"
    ad_group_history: "{% if var('generating_docs','no') == 'yes' %}{{ source('apple_search_ads','ad_group_history') }}{% else %}{{ ref('ad_group_history_data') }}{% endif %}"
    ad_group_report: "{% if var('generating_docs','no') == 'yes' %}{{ source('apple_search_ads','ad_group_report') }}{% else %}{{ ref('ad_group_report_data') }}{% endif %}"
    keyword_history: "{% if var('generating_docs','no') == 'yes' %}{{ source('apple_search_ads','keyword_history') }}{% else %}{{ ref('keyword_history_data') }}{% endif %}"
    keyword_report: "{% if var('generating_docs','no') == 'yes' %}{{ source('apple_search_ads','keyword_report') }}{% else %}{{ ref('keyword_report_data') }}{% endif %}"
    search_term_report: "{% if var('generating_docs','no') == 'yes' %}{{ source('apple_search_ads','search_term_report') }}{% else %}{{ ref('search_term_report_data') }}{% endif %}"
    apple_search_ads_schema: apple_search_ads_source_integration_tests


seeds:
  +quote_columns: "{{ true if target.type == 'redshift' else false }}"
  apple_search_ads_source_integration_tests:
    +column_types:
      _fivetran_synced: timestamp
    ad_group_history_data: 
      +column_types:
        modification_time: timestamp
        start_time: timestamp
        end_time: timestamp
    campaign_history_data:
      +column_types:
        modification_time: timestamp
        start_time: timestamp
        end_time: timestamp
    keyword_history_data:
      +column_types:
        modification_time: timestamp

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']