config-version: 2

name: 'apple_search_ads_source_integration_tests'
version: '0.1.0'

profile: 'integration_tests' 

vars:
  apple_search_ads_schema: apple_search_ads_source_integration_tests
  apple_search_ads_source:
    organization: "{{ ref('organization') }}"
    campaign_history: "{{ ref('campaign_history') }}"
    campaign_report: "{{ ref('campaign_report') }}"
    ad_group_history: "{{ ref('ad_group_history') }}"
    ad_group_report: "{{ ref('ad_group_report') }}"
    keyword_history: "{{ ref('keyword_history') }}"
    keyword_report: "{{ ref('keyword_report') }}"

seeds:
  +quote_columns: "{{ true if target.type == 'redshift' else false }}"
  apple_search_ads_source_integration_tests:
    +column_types:
      _fivetran_synced: timestamp
    ad_group_history: 
      +column_types:
        modification_time: timestamp
        start_time: timestamp
        end_time: timestamp
    campaign_history:
      +column_types:
        modification_time: timestamp
        start_time: timestamp
        end_time: timestamp
    keyword_history:
      +column_types:
        modification_time: timestamp

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']