config-version: 2

name: 'apple_search_ads_source_integration_tests'
version: '0.1.0'

profile: 'integration_tests' 

vars:
  apple_search_ads_schema: apple_search_ads_source_integration_tests
  apple_search_ads_source:
    organization: "{{ ref('organization_data') }}"
    campaign_history: "{{ ref('campaign_history_data') }}"
    campaign_report: "{{ ref('campaign_report_data') }}"
    ad_group_history: "{{ ref('ad_group_history_data') }}"
    ad_group_report: "{{ ref('ad_group_report_data') }}"
    keyword_history: "{{ ref('keyword_history_data') }}"
    keyword_report: "{{ ref('keyword_report_data') }}"

seeds:
  +quote_columns: "{{ true if target.type == 'redshift' else false }}"
  apple_search_ads_source_integration_tests:
    +column_types:
      _fivetran_synced: timestamp

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']